# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.8.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.8.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/gemini/Code/badvpn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/gemini/Code/badvpn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.8.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.8.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gemini/Code/badvpn/CMakeFiles /Users/gemini/Code/badvpn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/gemini/Code/badvpn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tun2socks

# Build rule for target.
tun2socks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tun2socks
.PHONY : tun2socks

# fast build rule for target.
tun2socks/fast:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/build
.PHONY : tun2socks/fast

base/BLog.o: base/BLog.c.o

.PHONY : base/BLog.o

# target to build an object file
base/BLog.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/BLog.c.o
.PHONY : base/BLog.c.o

base/BLog.i: base/BLog.c.i

.PHONY : base/BLog.i

# target to preprocess a source file
base/BLog.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/BLog.c.i
.PHONY : base/BLog.c.i

base/BLog.s: base/BLog.c.s

.PHONY : base/BLog.s

# target to generate assembly for a file
base/BLog.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/BLog.c.s
.PHONY : base/BLog.c.s

base/BLog_syslog.o: base/BLog_syslog.c.o

.PHONY : base/BLog_syslog.o

# target to build an object file
base/BLog_syslog.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/BLog_syslog.c.o
.PHONY : base/BLog_syslog.c.o

base/BLog_syslog.i: base/BLog_syslog.c.i

.PHONY : base/BLog_syslog.i

# target to preprocess a source file
base/BLog_syslog.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/BLog_syslog.c.i
.PHONY : base/BLog_syslog.c.i

base/BLog_syslog.s: base/BLog_syslog.c.s

.PHONY : base/BLog_syslog.s

# target to generate assembly for a file
base/BLog_syslog.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/BLog_syslog.c.s
.PHONY : base/BLog_syslog.c.s

base/BPending.o: base/BPending.c.o

.PHONY : base/BPending.o

# target to build an object file
base/BPending.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/BPending.c.o
.PHONY : base/BPending.c.o

base/BPending.i: base/BPending.c.i

.PHONY : base/BPending.i

# target to preprocess a source file
base/BPending.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/BPending.c.i
.PHONY : base/BPending.c.i

base/BPending.s: base/BPending.c.s

.PHONY : base/BPending.s

# target to generate assembly for a file
base/BPending.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/BPending.c.s
.PHONY : base/BPending.c.s

base/DebugObject.o: base/DebugObject.c.o

.PHONY : base/DebugObject.o

# target to build an object file
base/DebugObject.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/DebugObject.c.o
.PHONY : base/DebugObject.c.o

base/DebugObject.i: base/DebugObject.c.i

.PHONY : base/DebugObject.i

# target to preprocess a source file
base/DebugObject.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/DebugObject.c.i
.PHONY : base/DebugObject.c.i

base/DebugObject.s: base/DebugObject.c.s

.PHONY : base/DebugObject.s

# target to generate assembly for a file
base/DebugObject.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/base/DebugObject.c.s
.PHONY : base/DebugObject.c.s

flow/BufferWriter.o: flow/BufferWriter.c.o

.PHONY : flow/BufferWriter.o

# target to build an object file
flow/BufferWriter.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/BufferWriter.c.o
.PHONY : flow/BufferWriter.c.o

flow/BufferWriter.i: flow/BufferWriter.c.i

.PHONY : flow/BufferWriter.i

# target to preprocess a source file
flow/BufferWriter.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/BufferWriter.c.i
.PHONY : flow/BufferWriter.c.i

flow/BufferWriter.s: flow/BufferWriter.c.s

.PHONY : flow/BufferWriter.s

# target to generate assembly for a file
flow/BufferWriter.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/BufferWriter.c.s
.PHONY : flow/BufferWriter.c.s

flow/PacketBuffer.o: flow/PacketBuffer.c.o

.PHONY : flow/PacketBuffer.o

# target to build an object file
flow/PacketBuffer.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketBuffer.c.o
.PHONY : flow/PacketBuffer.c.o

flow/PacketBuffer.i: flow/PacketBuffer.c.i

.PHONY : flow/PacketBuffer.i

# target to preprocess a source file
flow/PacketBuffer.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketBuffer.c.i
.PHONY : flow/PacketBuffer.c.i

flow/PacketBuffer.s: flow/PacketBuffer.c.s

.PHONY : flow/PacketBuffer.s

# target to generate assembly for a file
flow/PacketBuffer.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketBuffer.c.s
.PHONY : flow/PacketBuffer.c.s

flow/PacketPassConnector.o: flow/PacketPassConnector.c.o

.PHONY : flow/PacketPassConnector.o

# target to build an object file
flow/PacketPassConnector.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketPassConnector.c.o
.PHONY : flow/PacketPassConnector.c.o

flow/PacketPassConnector.i: flow/PacketPassConnector.c.i

.PHONY : flow/PacketPassConnector.i

# target to preprocess a source file
flow/PacketPassConnector.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketPassConnector.c.i
.PHONY : flow/PacketPassConnector.c.i

flow/PacketPassConnector.s: flow/PacketPassConnector.c.s

.PHONY : flow/PacketPassConnector.s

# target to generate assembly for a file
flow/PacketPassConnector.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketPassConnector.c.s
.PHONY : flow/PacketPassConnector.c.s

flow/PacketPassFairQueue.o: flow/PacketPassFairQueue.c.o

.PHONY : flow/PacketPassFairQueue.o

# target to build an object file
flow/PacketPassFairQueue.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketPassFairQueue.c.o
.PHONY : flow/PacketPassFairQueue.c.o

flow/PacketPassFairQueue.i: flow/PacketPassFairQueue.c.i

.PHONY : flow/PacketPassFairQueue.i

# target to preprocess a source file
flow/PacketPassFairQueue.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketPassFairQueue.c.i
.PHONY : flow/PacketPassFairQueue.c.i

flow/PacketPassFairQueue.s: flow/PacketPassFairQueue.c.s

.PHONY : flow/PacketPassFairQueue.s

# target to generate assembly for a file
flow/PacketPassFairQueue.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketPassFairQueue.c.s
.PHONY : flow/PacketPassFairQueue.c.s

flow/PacketPassInterface.o: flow/PacketPassInterface.c.o

.PHONY : flow/PacketPassInterface.o

# target to build an object file
flow/PacketPassInterface.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketPassInterface.c.o
.PHONY : flow/PacketPassInterface.c.o

flow/PacketPassInterface.i: flow/PacketPassInterface.c.i

.PHONY : flow/PacketPassInterface.i

# target to preprocess a source file
flow/PacketPassInterface.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketPassInterface.c.i
.PHONY : flow/PacketPassInterface.c.i

flow/PacketPassInterface.s: flow/PacketPassInterface.c.s

.PHONY : flow/PacketPassInterface.s

# target to generate assembly for a file
flow/PacketPassInterface.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketPassInterface.c.s
.PHONY : flow/PacketPassInterface.c.s

flow/PacketProtoDecoder.o: flow/PacketProtoDecoder.c.o

.PHONY : flow/PacketProtoDecoder.o

# target to build an object file
flow/PacketProtoDecoder.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketProtoDecoder.c.o
.PHONY : flow/PacketProtoDecoder.c.o

flow/PacketProtoDecoder.i: flow/PacketProtoDecoder.c.i

.PHONY : flow/PacketProtoDecoder.i

# target to preprocess a source file
flow/PacketProtoDecoder.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketProtoDecoder.c.i
.PHONY : flow/PacketProtoDecoder.c.i

flow/PacketProtoDecoder.s: flow/PacketProtoDecoder.c.s

.PHONY : flow/PacketProtoDecoder.s

# target to generate assembly for a file
flow/PacketProtoDecoder.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketProtoDecoder.c.s
.PHONY : flow/PacketProtoDecoder.c.s

flow/PacketProtoEncoder.o: flow/PacketProtoEncoder.c.o

.PHONY : flow/PacketProtoEncoder.o

# target to build an object file
flow/PacketProtoEncoder.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketProtoEncoder.c.o
.PHONY : flow/PacketProtoEncoder.c.o

flow/PacketProtoEncoder.i: flow/PacketProtoEncoder.c.i

.PHONY : flow/PacketProtoEncoder.i

# target to preprocess a source file
flow/PacketProtoEncoder.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketProtoEncoder.c.i
.PHONY : flow/PacketProtoEncoder.c.i

flow/PacketProtoEncoder.s: flow/PacketProtoEncoder.c.s

.PHONY : flow/PacketProtoEncoder.s

# target to generate assembly for a file
flow/PacketProtoEncoder.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketProtoEncoder.c.s
.PHONY : flow/PacketProtoEncoder.c.s

flow/PacketProtoFlow.o: flow/PacketProtoFlow.c.o

.PHONY : flow/PacketProtoFlow.o

# target to build an object file
flow/PacketProtoFlow.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketProtoFlow.c.o
.PHONY : flow/PacketProtoFlow.c.o

flow/PacketProtoFlow.i: flow/PacketProtoFlow.c.i

.PHONY : flow/PacketProtoFlow.i

# target to preprocess a source file
flow/PacketProtoFlow.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketProtoFlow.c.i
.PHONY : flow/PacketProtoFlow.c.i

flow/PacketProtoFlow.s: flow/PacketProtoFlow.c.s

.PHONY : flow/PacketProtoFlow.s

# target to generate assembly for a file
flow/PacketProtoFlow.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketProtoFlow.c.s
.PHONY : flow/PacketProtoFlow.c.s

flow/PacketRecvInterface.o: flow/PacketRecvInterface.c.o

.PHONY : flow/PacketRecvInterface.o

# target to build an object file
flow/PacketRecvInterface.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketRecvInterface.c.o
.PHONY : flow/PacketRecvInterface.c.o

flow/PacketRecvInterface.i: flow/PacketRecvInterface.c.i

.PHONY : flow/PacketRecvInterface.i

# target to preprocess a source file
flow/PacketRecvInterface.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketRecvInterface.c.i
.PHONY : flow/PacketRecvInterface.c.i

flow/PacketRecvInterface.s: flow/PacketRecvInterface.c.s

.PHONY : flow/PacketRecvInterface.s

# target to generate assembly for a file
flow/PacketRecvInterface.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketRecvInterface.c.s
.PHONY : flow/PacketRecvInterface.c.s

flow/PacketStreamSender.o: flow/PacketStreamSender.c.o

.PHONY : flow/PacketStreamSender.o

# target to build an object file
flow/PacketStreamSender.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketStreamSender.c.o
.PHONY : flow/PacketStreamSender.c.o

flow/PacketStreamSender.i: flow/PacketStreamSender.c.i

.PHONY : flow/PacketStreamSender.i

# target to preprocess a source file
flow/PacketStreamSender.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketStreamSender.c.i
.PHONY : flow/PacketStreamSender.c.i

flow/PacketStreamSender.s: flow/PacketStreamSender.c.s

.PHONY : flow/PacketStreamSender.s

# target to generate assembly for a file
flow/PacketStreamSender.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/PacketStreamSender.c.s
.PHONY : flow/PacketStreamSender.c.s

flow/SinglePacketBuffer.o: flow/SinglePacketBuffer.c.o

.PHONY : flow/SinglePacketBuffer.o

# target to build an object file
flow/SinglePacketBuffer.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/SinglePacketBuffer.c.o
.PHONY : flow/SinglePacketBuffer.c.o

flow/SinglePacketBuffer.i: flow/SinglePacketBuffer.c.i

.PHONY : flow/SinglePacketBuffer.i

# target to preprocess a source file
flow/SinglePacketBuffer.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/SinglePacketBuffer.c.i
.PHONY : flow/SinglePacketBuffer.c.i

flow/SinglePacketBuffer.s: flow/SinglePacketBuffer.c.s

.PHONY : flow/SinglePacketBuffer.s

# target to generate assembly for a file
flow/SinglePacketBuffer.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/SinglePacketBuffer.c.s
.PHONY : flow/SinglePacketBuffer.c.s

flow/StreamPassInterface.o: flow/StreamPassInterface.c.o

.PHONY : flow/StreamPassInterface.o

# target to build an object file
flow/StreamPassInterface.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/StreamPassInterface.c.o
.PHONY : flow/StreamPassInterface.c.o

flow/StreamPassInterface.i: flow/StreamPassInterface.c.i

.PHONY : flow/StreamPassInterface.i

# target to preprocess a source file
flow/StreamPassInterface.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/StreamPassInterface.c.i
.PHONY : flow/StreamPassInterface.c.i

flow/StreamPassInterface.s: flow/StreamPassInterface.c.s

.PHONY : flow/StreamPassInterface.s

# target to generate assembly for a file
flow/StreamPassInterface.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/StreamPassInterface.c.s
.PHONY : flow/StreamPassInterface.c.s

flow/StreamRecvInterface.o: flow/StreamRecvInterface.c.o

.PHONY : flow/StreamRecvInterface.o

# target to build an object file
flow/StreamRecvInterface.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/StreamRecvInterface.c.o
.PHONY : flow/StreamRecvInterface.c.o

flow/StreamRecvInterface.i: flow/StreamRecvInterface.c.i

.PHONY : flow/StreamRecvInterface.i

# target to preprocess a source file
flow/StreamRecvInterface.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/StreamRecvInterface.c.i
.PHONY : flow/StreamRecvInterface.c.i

flow/StreamRecvInterface.s: flow/StreamRecvInterface.c.s

.PHONY : flow/StreamRecvInterface.s

# target to generate assembly for a file
flow/StreamRecvInterface.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flow/StreamRecvInterface.c.s
.PHONY : flow/StreamRecvInterface.c.s

flowextra/PacketPassInactivityMonitor.o: flowextra/PacketPassInactivityMonitor.c.o

.PHONY : flowextra/PacketPassInactivityMonitor.o

# target to build an object file
flowextra/PacketPassInactivityMonitor.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flowextra/PacketPassInactivityMonitor.c.o
.PHONY : flowextra/PacketPassInactivityMonitor.c.o

flowextra/PacketPassInactivityMonitor.i: flowextra/PacketPassInactivityMonitor.c.i

.PHONY : flowextra/PacketPassInactivityMonitor.i

# target to preprocess a source file
flowextra/PacketPassInactivityMonitor.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flowextra/PacketPassInactivityMonitor.c.i
.PHONY : flowextra/PacketPassInactivityMonitor.c.i

flowextra/PacketPassInactivityMonitor.s: flowextra/PacketPassInactivityMonitor.c.s

.PHONY : flowextra/PacketPassInactivityMonitor.s

# target to generate assembly for a file
flowextra/PacketPassInactivityMonitor.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/flowextra/PacketPassInactivityMonitor.c.s
.PHONY : flowextra/PacketPassInactivityMonitor.c.s

libancillary/fd_recv.o: libancillary/fd_recv.c.o

.PHONY : libancillary/fd_recv.o

# target to build an object file
libancillary/fd_recv.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/libancillary/fd_recv.c.o
.PHONY : libancillary/fd_recv.c.o

libancillary/fd_recv.i: libancillary/fd_recv.c.i

.PHONY : libancillary/fd_recv.i

# target to preprocess a source file
libancillary/fd_recv.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/libancillary/fd_recv.c.i
.PHONY : libancillary/fd_recv.c.i

libancillary/fd_recv.s: libancillary/fd_recv.c.s

.PHONY : libancillary/fd_recv.s

# target to generate assembly for a file
libancillary/fd_recv.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/libancillary/fd_recv.c.s
.PHONY : libancillary/fd_recv.c.s

libancillary/fd_send.o: libancillary/fd_send.c.o

.PHONY : libancillary/fd_send.o

# target to build an object file
libancillary/fd_send.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/libancillary/fd_send.c.o
.PHONY : libancillary/fd_send.c.o

libancillary/fd_send.i: libancillary/fd_send.c.i

.PHONY : libancillary/fd_send.i

# target to preprocess a source file
libancillary/fd_send.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/libancillary/fd_send.c.i
.PHONY : libancillary/fd_send.c.i

libancillary/fd_send.s: libancillary/fd_send.c.s

.PHONY : libancillary/fd_send.s

# target to generate assembly for a file
libancillary/fd_send.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/libancillary/fd_send.c.s
.PHONY : libancillary/fd_send.c.s

lwip/custom/sys.o: lwip/custom/sys.c.o

.PHONY : lwip/custom/sys.o

# target to build an object file
lwip/custom/sys.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/custom/sys.c.o
.PHONY : lwip/custom/sys.c.o

lwip/custom/sys.i: lwip/custom/sys.c.i

.PHONY : lwip/custom/sys.i

# target to preprocess a source file
lwip/custom/sys.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/custom/sys.c.i
.PHONY : lwip/custom/sys.c.i

lwip/custom/sys.s: lwip/custom/sys.c.s

.PHONY : lwip/custom/sys.s

# target to generate assembly for a file
lwip/custom/sys.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/custom/sys.c.s
.PHONY : lwip/custom/sys.c.s

lwip/src/core/def.o: lwip/src/core/def.c.o

.PHONY : lwip/src/core/def.o

# target to build an object file
lwip/src/core/def.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/def.c.o
.PHONY : lwip/src/core/def.c.o

lwip/src/core/def.i: lwip/src/core/def.c.i

.PHONY : lwip/src/core/def.i

# target to preprocess a source file
lwip/src/core/def.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/def.c.i
.PHONY : lwip/src/core/def.c.i

lwip/src/core/def.s: lwip/src/core/def.c.s

.PHONY : lwip/src/core/def.s

# target to generate assembly for a file
lwip/src/core/def.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/def.c.s
.PHONY : lwip/src/core/def.c.s

lwip/src/core/inet_chksum.o: lwip/src/core/inet_chksum.c.o

.PHONY : lwip/src/core/inet_chksum.o

# target to build an object file
lwip/src/core/inet_chksum.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/inet_chksum.c.o
.PHONY : lwip/src/core/inet_chksum.c.o

lwip/src/core/inet_chksum.i: lwip/src/core/inet_chksum.c.i

.PHONY : lwip/src/core/inet_chksum.i

# target to preprocess a source file
lwip/src/core/inet_chksum.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/inet_chksum.c.i
.PHONY : lwip/src/core/inet_chksum.c.i

lwip/src/core/inet_chksum.s: lwip/src/core/inet_chksum.c.s

.PHONY : lwip/src/core/inet_chksum.s

# target to generate assembly for a file
lwip/src/core/inet_chksum.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/inet_chksum.c.s
.PHONY : lwip/src/core/inet_chksum.c.s

lwip/src/core/init.o: lwip/src/core/init.c.o

.PHONY : lwip/src/core/init.o

# target to build an object file
lwip/src/core/init.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/init.c.o
.PHONY : lwip/src/core/init.c.o

lwip/src/core/init.i: lwip/src/core/init.c.i

.PHONY : lwip/src/core/init.i

# target to preprocess a source file
lwip/src/core/init.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/init.c.i
.PHONY : lwip/src/core/init.c.i

lwip/src/core/init.s: lwip/src/core/init.c.s

.PHONY : lwip/src/core/init.s

# target to generate assembly for a file
lwip/src/core/init.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/init.c.s
.PHONY : lwip/src/core/init.c.s

lwip/src/core/ipv4/autoip.o: lwip/src/core/ipv4/autoip.c.o

.PHONY : lwip/src/core/ipv4/autoip.o

# target to build an object file
lwip/src/core/ipv4/autoip.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/autoip.c.o
.PHONY : lwip/src/core/ipv4/autoip.c.o

lwip/src/core/ipv4/autoip.i: lwip/src/core/ipv4/autoip.c.i

.PHONY : lwip/src/core/ipv4/autoip.i

# target to preprocess a source file
lwip/src/core/ipv4/autoip.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/autoip.c.i
.PHONY : lwip/src/core/ipv4/autoip.c.i

lwip/src/core/ipv4/autoip.s: lwip/src/core/ipv4/autoip.c.s

.PHONY : lwip/src/core/ipv4/autoip.s

# target to generate assembly for a file
lwip/src/core/ipv4/autoip.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/autoip.c.s
.PHONY : lwip/src/core/ipv4/autoip.c.s

lwip/src/core/ipv4/icmp.o: lwip/src/core/ipv4/icmp.c.o

.PHONY : lwip/src/core/ipv4/icmp.o

# target to build an object file
lwip/src/core/ipv4/icmp.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/icmp.c.o
.PHONY : lwip/src/core/ipv4/icmp.c.o

lwip/src/core/ipv4/icmp.i: lwip/src/core/ipv4/icmp.c.i

.PHONY : lwip/src/core/ipv4/icmp.i

# target to preprocess a source file
lwip/src/core/ipv4/icmp.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/icmp.c.i
.PHONY : lwip/src/core/ipv4/icmp.c.i

lwip/src/core/ipv4/icmp.s: lwip/src/core/ipv4/icmp.c.s

.PHONY : lwip/src/core/ipv4/icmp.s

# target to generate assembly for a file
lwip/src/core/ipv4/icmp.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/icmp.c.s
.PHONY : lwip/src/core/ipv4/icmp.c.s

lwip/src/core/ipv4/igmp.o: lwip/src/core/ipv4/igmp.c.o

.PHONY : lwip/src/core/ipv4/igmp.o

# target to build an object file
lwip/src/core/ipv4/igmp.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/igmp.c.o
.PHONY : lwip/src/core/ipv4/igmp.c.o

lwip/src/core/ipv4/igmp.i: lwip/src/core/ipv4/igmp.c.i

.PHONY : lwip/src/core/ipv4/igmp.i

# target to preprocess a source file
lwip/src/core/ipv4/igmp.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/igmp.c.i
.PHONY : lwip/src/core/ipv4/igmp.c.i

lwip/src/core/ipv4/igmp.s: lwip/src/core/ipv4/igmp.c.s

.PHONY : lwip/src/core/ipv4/igmp.s

# target to generate assembly for a file
lwip/src/core/ipv4/igmp.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/igmp.c.s
.PHONY : lwip/src/core/ipv4/igmp.c.s

lwip/src/core/ipv4/ip4.o: lwip/src/core/ipv4/ip4.c.o

.PHONY : lwip/src/core/ipv4/ip4.o

# target to build an object file
lwip/src/core/ipv4/ip4.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/ip4.c.o
.PHONY : lwip/src/core/ipv4/ip4.c.o

lwip/src/core/ipv4/ip4.i: lwip/src/core/ipv4/ip4.c.i

.PHONY : lwip/src/core/ipv4/ip4.i

# target to preprocess a source file
lwip/src/core/ipv4/ip4.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/ip4.c.i
.PHONY : lwip/src/core/ipv4/ip4.c.i

lwip/src/core/ipv4/ip4.s: lwip/src/core/ipv4/ip4.c.s

.PHONY : lwip/src/core/ipv4/ip4.s

# target to generate assembly for a file
lwip/src/core/ipv4/ip4.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/ip4.c.s
.PHONY : lwip/src/core/ipv4/ip4.c.s

lwip/src/core/ipv4/ip4_addr.o: lwip/src/core/ipv4/ip4_addr.c.o

.PHONY : lwip/src/core/ipv4/ip4_addr.o

# target to build an object file
lwip/src/core/ipv4/ip4_addr.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/ip4_addr.c.o
.PHONY : lwip/src/core/ipv4/ip4_addr.c.o

lwip/src/core/ipv4/ip4_addr.i: lwip/src/core/ipv4/ip4_addr.c.i

.PHONY : lwip/src/core/ipv4/ip4_addr.i

# target to preprocess a source file
lwip/src/core/ipv4/ip4_addr.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/ip4_addr.c.i
.PHONY : lwip/src/core/ipv4/ip4_addr.c.i

lwip/src/core/ipv4/ip4_addr.s: lwip/src/core/ipv4/ip4_addr.c.s

.PHONY : lwip/src/core/ipv4/ip4_addr.s

# target to generate assembly for a file
lwip/src/core/ipv4/ip4_addr.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/ip4_addr.c.s
.PHONY : lwip/src/core/ipv4/ip4_addr.c.s

lwip/src/core/ipv4/ip_frag.o: lwip/src/core/ipv4/ip_frag.c.o

.PHONY : lwip/src/core/ipv4/ip_frag.o

# target to build an object file
lwip/src/core/ipv4/ip_frag.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/ip_frag.c.o
.PHONY : lwip/src/core/ipv4/ip_frag.c.o

lwip/src/core/ipv4/ip_frag.i: lwip/src/core/ipv4/ip_frag.c.i

.PHONY : lwip/src/core/ipv4/ip_frag.i

# target to preprocess a source file
lwip/src/core/ipv4/ip_frag.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/ip_frag.c.i
.PHONY : lwip/src/core/ipv4/ip_frag.c.i

lwip/src/core/ipv4/ip_frag.s: lwip/src/core/ipv4/ip_frag.c.s

.PHONY : lwip/src/core/ipv4/ip_frag.s

# target to generate assembly for a file
lwip/src/core/ipv4/ip_frag.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv4/ip_frag.c.s
.PHONY : lwip/src/core/ipv4/ip_frag.c.s

lwip/src/core/ipv6/dhcp6.o: lwip/src/core/ipv6/dhcp6.c.o

.PHONY : lwip/src/core/ipv6/dhcp6.o

# target to build an object file
lwip/src/core/ipv6/dhcp6.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/dhcp6.c.o
.PHONY : lwip/src/core/ipv6/dhcp6.c.o

lwip/src/core/ipv6/dhcp6.i: lwip/src/core/ipv6/dhcp6.c.i

.PHONY : lwip/src/core/ipv6/dhcp6.i

# target to preprocess a source file
lwip/src/core/ipv6/dhcp6.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/dhcp6.c.i
.PHONY : lwip/src/core/ipv6/dhcp6.c.i

lwip/src/core/ipv6/dhcp6.s: lwip/src/core/ipv6/dhcp6.c.s

.PHONY : lwip/src/core/ipv6/dhcp6.s

# target to generate assembly for a file
lwip/src/core/ipv6/dhcp6.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/dhcp6.c.s
.PHONY : lwip/src/core/ipv6/dhcp6.c.s

lwip/src/core/ipv6/ethip6.o: lwip/src/core/ipv6/ethip6.c.o

.PHONY : lwip/src/core/ipv6/ethip6.o

# target to build an object file
lwip/src/core/ipv6/ethip6.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ethip6.c.o
.PHONY : lwip/src/core/ipv6/ethip6.c.o

lwip/src/core/ipv6/ethip6.i: lwip/src/core/ipv6/ethip6.c.i

.PHONY : lwip/src/core/ipv6/ethip6.i

# target to preprocess a source file
lwip/src/core/ipv6/ethip6.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ethip6.c.i
.PHONY : lwip/src/core/ipv6/ethip6.c.i

lwip/src/core/ipv6/ethip6.s: lwip/src/core/ipv6/ethip6.c.s

.PHONY : lwip/src/core/ipv6/ethip6.s

# target to generate assembly for a file
lwip/src/core/ipv6/ethip6.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ethip6.c.s
.PHONY : lwip/src/core/ipv6/ethip6.c.s

lwip/src/core/ipv6/icmp6.o: lwip/src/core/ipv6/icmp6.c.o

.PHONY : lwip/src/core/ipv6/icmp6.o

# target to build an object file
lwip/src/core/ipv6/icmp6.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/icmp6.c.o
.PHONY : lwip/src/core/ipv6/icmp6.c.o

lwip/src/core/ipv6/icmp6.i: lwip/src/core/ipv6/icmp6.c.i

.PHONY : lwip/src/core/ipv6/icmp6.i

# target to preprocess a source file
lwip/src/core/ipv6/icmp6.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/icmp6.c.i
.PHONY : lwip/src/core/ipv6/icmp6.c.i

lwip/src/core/ipv6/icmp6.s: lwip/src/core/ipv6/icmp6.c.s

.PHONY : lwip/src/core/ipv6/icmp6.s

# target to generate assembly for a file
lwip/src/core/ipv6/icmp6.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/icmp6.c.s
.PHONY : lwip/src/core/ipv6/icmp6.c.s

lwip/src/core/ipv6/inet6.o: lwip/src/core/ipv6/inet6.c.o

.PHONY : lwip/src/core/ipv6/inet6.o

# target to build an object file
lwip/src/core/ipv6/inet6.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/inet6.c.o
.PHONY : lwip/src/core/ipv6/inet6.c.o

lwip/src/core/ipv6/inet6.i: lwip/src/core/ipv6/inet6.c.i

.PHONY : lwip/src/core/ipv6/inet6.i

# target to preprocess a source file
lwip/src/core/ipv6/inet6.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/inet6.c.i
.PHONY : lwip/src/core/ipv6/inet6.c.i

lwip/src/core/ipv6/inet6.s: lwip/src/core/ipv6/inet6.c.s

.PHONY : lwip/src/core/ipv6/inet6.s

# target to generate assembly for a file
lwip/src/core/ipv6/inet6.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/inet6.c.s
.PHONY : lwip/src/core/ipv6/inet6.c.s

lwip/src/core/ipv6/ip6.o: lwip/src/core/ipv6/ip6.c.o

.PHONY : lwip/src/core/ipv6/ip6.o

# target to build an object file
lwip/src/core/ipv6/ip6.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ip6.c.o
.PHONY : lwip/src/core/ipv6/ip6.c.o

lwip/src/core/ipv6/ip6.i: lwip/src/core/ipv6/ip6.c.i

.PHONY : lwip/src/core/ipv6/ip6.i

# target to preprocess a source file
lwip/src/core/ipv6/ip6.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ip6.c.i
.PHONY : lwip/src/core/ipv6/ip6.c.i

lwip/src/core/ipv6/ip6.s: lwip/src/core/ipv6/ip6.c.s

.PHONY : lwip/src/core/ipv6/ip6.s

# target to generate assembly for a file
lwip/src/core/ipv6/ip6.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ip6.c.s
.PHONY : lwip/src/core/ipv6/ip6.c.s

lwip/src/core/ipv6/ip6_addr.o: lwip/src/core/ipv6/ip6_addr.c.o

.PHONY : lwip/src/core/ipv6/ip6_addr.o

# target to build an object file
lwip/src/core/ipv6/ip6_addr.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ip6_addr.c.o
.PHONY : lwip/src/core/ipv6/ip6_addr.c.o

lwip/src/core/ipv6/ip6_addr.i: lwip/src/core/ipv6/ip6_addr.c.i

.PHONY : lwip/src/core/ipv6/ip6_addr.i

# target to preprocess a source file
lwip/src/core/ipv6/ip6_addr.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ip6_addr.c.i
.PHONY : lwip/src/core/ipv6/ip6_addr.c.i

lwip/src/core/ipv6/ip6_addr.s: lwip/src/core/ipv6/ip6_addr.c.s

.PHONY : lwip/src/core/ipv6/ip6_addr.s

# target to generate assembly for a file
lwip/src/core/ipv6/ip6_addr.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ip6_addr.c.s
.PHONY : lwip/src/core/ipv6/ip6_addr.c.s

lwip/src/core/ipv6/ip6_frag.o: lwip/src/core/ipv6/ip6_frag.c.o

.PHONY : lwip/src/core/ipv6/ip6_frag.o

# target to build an object file
lwip/src/core/ipv6/ip6_frag.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ip6_frag.c.o
.PHONY : lwip/src/core/ipv6/ip6_frag.c.o

lwip/src/core/ipv6/ip6_frag.i: lwip/src/core/ipv6/ip6_frag.c.i

.PHONY : lwip/src/core/ipv6/ip6_frag.i

# target to preprocess a source file
lwip/src/core/ipv6/ip6_frag.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ip6_frag.c.i
.PHONY : lwip/src/core/ipv6/ip6_frag.c.i

lwip/src/core/ipv6/ip6_frag.s: lwip/src/core/ipv6/ip6_frag.c.s

.PHONY : lwip/src/core/ipv6/ip6_frag.s

# target to generate assembly for a file
lwip/src/core/ipv6/ip6_frag.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/ip6_frag.c.s
.PHONY : lwip/src/core/ipv6/ip6_frag.c.s

lwip/src/core/ipv6/mld6.o: lwip/src/core/ipv6/mld6.c.o

.PHONY : lwip/src/core/ipv6/mld6.o

# target to build an object file
lwip/src/core/ipv6/mld6.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/mld6.c.o
.PHONY : lwip/src/core/ipv6/mld6.c.o

lwip/src/core/ipv6/mld6.i: lwip/src/core/ipv6/mld6.c.i

.PHONY : lwip/src/core/ipv6/mld6.i

# target to preprocess a source file
lwip/src/core/ipv6/mld6.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/mld6.c.i
.PHONY : lwip/src/core/ipv6/mld6.c.i

lwip/src/core/ipv6/mld6.s: lwip/src/core/ipv6/mld6.c.s

.PHONY : lwip/src/core/ipv6/mld6.s

# target to generate assembly for a file
lwip/src/core/ipv6/mld6.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/mld6.c.s
.PHONY : lwip/src/core/ipv6/mld6.c.s

lwip/src/core/ipv6/nd6.o: lwip/src/core/ipv6/nd6.c.o

.PHONY : lwip/src/core/ipv6/nd6.o

# target to build an object file
lwip/src/core/ipv6/nd6.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/nd6.c.o
.PHONY : lwip/src/core/ipv6/nd6.c.o

lwip/src/core/ipv6/nd6.i: lwip/src/core/ipv6/nd6.c.i

.PHONY : lwip/src/core/ipv6/nd6.i

# target to preprocess a source file
lwip/src/core/ipv6/nd6.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/nd6.c.i
.PHONY : lwip/src/core/ipv6/nd6.c.i

lwip/src/core/ipv6/nd6.s: lwip/src/core/ipv6/nd6.c.s

.PHONY : lwip/src/core/ipv6/nd6.s

# target to generate assembly for a file
lwip/src/core/ipv6/nd6.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/ipv6/nd6.c.s
.PHONY : lwip/src/core/ipv6/nd6.c.s

lwip/src/core/mem.o: lwip/src/core/mem.c.o

.PHONY : lwip/src/core/mem.o

# target to build an object file
lwip/src/core/mem.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/mem.c.o
.PHONY : lwip/src/core/mem.c.o

lwip/src/core/mem.i: lwip/src/core/mem.c.i

.PHONY : lwip/src/core/mem.i

# target to preprocess a source file
lwip/src/core/mem.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/mem.c.i
.PHONY : lwip/src/core/mem.c.i

lwip/src/core/mem.s: lwip/src/core/mem.c.s

.PHONY : lwip/src/core/mem.s

# target to generate assembly for a file
lwip/src/core/mem.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/mem.c.s
.PHONY : lwip/src/core/mem.c.s

lwip/src/core/memp.o: lwip/src/core/memp.c.o

.PHONY : lwip/src/core/memp.o

# target to build an object file
lwip/src/core/memp.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/memp.c.o
.PHONY : lwip/src/core/memp.c.o

lwip/src/core/memp.i: lwip/src/core/memp.c.i

.PHONY : lwip/src/core/memp.i

# target to preprocess a source file
lwip/src/core/memp.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/memp.c.i
.PHONY : lwip/src/core/memp.c.i

lwip/src/core/memp.s: lwip/src/core/memp.c.s

.PHONY : lwip/src/core/memp.s

# target to generate assembly for a file
lwip/src/core/memp.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/memp.c.s
.PHONY : lwip/src/core/memp.c.s

lwip/src/core/netif.o: lwip/src/core/netif.c.o

.PHONY : lwip/src/core/netif.o

# target to build an object file
lwip/src/core/netif.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/netif.c.o
.PHONY : lwip/src/core/netif.c.o

lwip/src/core/netif.i: lwip/src/core/netif.c.i

.PHONY : lwip/src/core/netif.i

# target to preprocess a source file
lwip/src/core/netif.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/netif.c.i
.PHONY : lwip/src/core/netif.c.i

lwip/src/core/netif.s: lwip/src/core/netif.c.s

.PHONY : lwip/src/core/netif.s

# target to generate assembly for a file
lwip/src/core/netif.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/netif.c.s
.PHONY : lwip/src/core/netif.c.s

lwip/src/core/pbuf.o: lwip/src/core/pbuf.c.o

.PHONY : lwip/src/core/pbuf.o

# target to build an object file
lwip/src/core/pbuf.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/pbuf.c.o
.PHONY : lwip/src/core/pbuf.c.o

lwip/src/core/pbuf.i: lwip/src/core/pbuf.c.i

.PHONY : lwip/src/core/pbuf.i

# target to preprocess a source file
lwip/src/core/pbuf.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/pbuf.c.i
.PHONY : lwip/src/core/pbuf.c.i

lwip/src/core/pbuf.s: lwip/src/core/pbuf.c.s

.PHONY : lwip/src/core/pbuf.s

# target to generate assembly for a file
lwip/src/core/pbuf.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/pbuf.c.s
.PHONY : lwip/src/core/pbuf.c.s

lwip/src/core/stats.o: lwip/src/core/stats.c.o

.PHONY : lwip/src/core/stats.o

# target to build an object file
lwip/src/core/stats.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/stats.c.o
.PHONY : lwip/src/core/stats.c.o

lwip/src/core/stats.i: lwip/src/core/stats.c.i

.PHONY : lwip/src/core/stats.i

# target to preprocess a source file
lwip/src/core/stats.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/stats.c.i
.PHONY : lwip/src/core/stats.c.i

lwip/src/core/stats.s: lwip/src/core/stats.c.s

.PHONY : lwip/src/core/stats.s

# target to generate assembly for a file
lwip/src/core/stats.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/stats.c.s
.PHONY : lwip/src/core/stats.c.s

lwip/src/core/tcp.o: lwip/src/core/tcp.c.o

.PHONY : lwip/src/core/tcp.o

# target to build an object file
lwip/src/core/tcp.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/tcp.c.o
.PHONY : lwip/src/core/tcp.c.o

lwip/src/core/tcp.i: lwip/src/core/tcp.c.i

.PHONY : lwip/src/core/tcp.i

# target to preprocess a source file
lwip/src/core/tcp.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/tcp.c.i
.PHONY : lwip/src/core/tcp.c.i

lwip/src/core/tcp.s: lwip/src/core/tcp.c.s

.PHONY : lwip/src/core/tcp.s

# target to generate assembly for a file
lwip/src/core/tcp.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/tcp.c.s
.PHONY : lwip/src/core/tcp.c.s

lwip/src/core/tcp_in.o: lwip/src/core/tcp_in.c.o

.PHONY : lwip/src/core/tcp_in.o

# target to build an object file
lwip/src/core/tcp_in.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/tcp_in.c.o
.PHONY : lwip/src/core/tcp_in.c.o

lwip/src/core/tcp_in.i: lwip/src/core/tcp_in.c.i

.PHONY : lwip/src/core/tcp_in.i

# target to preprocess a source file
lwip/src/core/tcp_in.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/tcp_in.c.i
.PHONY : lwip/src/core/tcp_in.c.i

lwip/src/core/tcp_in.s: lwip/src/core/tcp_in.c.s

.PHONY : lwip/src/core/tcp_in.s

# target to generate assembly for a file
lwip/src/core/tcp_in.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/tcp_in.c.s
.PHONY : lwip/src/core/tcp_in.c.s

lwip/src/core/tcp_out.o: lwip/src/core/tcp_out.c.o

.PHONY : lwip/src/core/tcp_out.o

# target to build an object file
lwip/src/core/tcp_out.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/tcp_out.c.o
.PHONY : lwip/src/core/tcp_out.c.o

lwip/src/core/tcp_out.i: lwip/src/core/tcp_out.c.i

.PHONY : lwip/src/core/tcp_out.i

# target to preprocess a source file
lwip/src/core/tcp_out.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/tcp_out.c.i
.PHONY : lwip/src/core/tcp_out.c.i

lwip/src/core/tcp_out.s: lwip/src/core/tcp_out.c.s

.PHONY : lwip/src/core/tcp_out.s

# target to generate assembly for a file
lwip/src/core/tcp_out.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/tcp_out.c.s
.PHONY : lwip/src/core/tcp_out.c.s

lwip/src/core/timers.o: lwip/src/core/timers.c.o

.PHONY : lwip/src/core/timers.o

# target to build an object file
lwip/src/core/timers.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/timers.c.o
.PHONY : lwip/src/core/timers.c.o

lwip/src/core/timers.i: lwip/src/core/timers.c.i

.PHONY : lwip/src/core/timers.i

# target to preprocess a source file
lwip/src/core/timers.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/timers.c.i
.PHONY : lwip/src/core/timers.c.i

lwip/src/core/timers.s: lwip/src/core/timers.c.s

.PHONY : lwip/src/core/timers.s

# target to generate assembly for a file
lwip/src/core/timers.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/timers.c.s
.PHONY : lwip/src/core/timers.c.s

lwip/src/core/udp.o: lwip/src/core/udp.c.o

.PHONY : lwip/src/core/udp.o

# target to build an object file
lwip/src/core/udp.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/udp.c.o
.PHONY : lwip/src/core/udp.c.o

lwip/src/core/udp.i: lwip/src/core/udp.c.i

.PHONY : lwip/src/core/udp.i

# target to preprocess a source file
lwip/src/core/udp.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/udp.c.i
.PHONY : lwip/src/core/udp.c.i

lwip/src/core/udp.s: lwip/src/core/udp.c.s

.PHONY : lwip/src/core/udp.s

# target to generate assembly for a file
lwip/src/core/udp.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/lwip/src/core/udp.c.s
.PHONY : lwip/src/core/udp.c.s

socksclient/BSocksClient.o: socksclient/BSocksClient.c.o

.PHONY : socksclient/BSocksClient.o

# target to build an object file
socksclient/BSocksClient.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/socksclient/BSocksClient.c.o
.PHONY : socksclient/BSocksClient.c.o

socksclient/BSocksClient.i: socksclient/BSocksClient.c.i

.PHONY : socksclient/BSocksClient.i

# target to preprocess a source file
socksclient/BSocksClient.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/socksclient/BSocksClient.c.i
.PHONY : socksclient/BSocksClient.c.i

socksclient/BSocksClient.s: socksclient/BSocksClient.c.s

.PHONY : socksclient/BSocksClient.s

# target to generate assembly for a file
socksclient/BSocksClient.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/socksclient/BSocksClient.c.s
.PHONY : socksclient/BSocksClient.c.s

system/BConnection_common.o: system/BConnection_common.c.o

.PHONY : system/BConnection_common.o

# target to build an object file
system/BConnection_common.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BConnection_common.c.o
.PHONY : system/BConnection_common.c.o

system/BConnection_common.i: system/BConnection_common.c.i

.PHONY : system/BConnection_common.i

# target to preprocess a source file
system/BConnection_common.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BConnection_common.c.i
.PHONY : system/BConnection_common.c.i

system/BConnection_common.s: system/BConnection_common.c.s

.PHONY : system/BConnection_common.s

# target to generate assembly for a file
system/BConnection_common.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BConnection_common.c.s
.PHONY : system/BConnection_common.c.s

system/BConnection_unix.o: system/BConnection_unix.c.o

.PHONY : system/BConnection_unix.o

# target to build an object file
system/BConnection_unix.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BConnection_unix.c.o
.PHONY : system/BConnection_unix.c.o

system/BConnection_unix.i: system/BConnection_unix.c.i

.PHONY : system/BConnection_unix.i

# target to preprocess a source file
system/BConnection_unix.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BConnection_unix.c.i
.PHONY : system/BConnection_unix.c.i

system/BConnection_unix.s: system/BConnection_unix.c.s

.PHONY : system/BConnection_unix.s

# target to generate assembly for a file
system/BConnection_unix.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BConnection_unix.c.s
.PHONY : system/BConnection_unix.c.s

system/BDatagram_unix.o: system/BDatagram_unix.c.o

.PHONY : system/BDatagram_unix.o

# target to build an object file
system/BDatagram_unix.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BDatagram_unix.c.o
.PHONY : system/BDatagram_unix.c.o

system/BDatagram_unix.i: system/BDatagram_unix.c.i

.PHONY : system/BDatagram_unix.i

# target to preprocess a source file
system/BDatagram_unix.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BDatagram_unix.c.i
.PHONY : system/BDatagram_unix.c.i

system/BDatagram_unix.s: system/BDatagram_unix.c.s

.PHONY : system/BDatagram_unix.s

# target to generate assembly for a file
system/BDatagram_unix.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BDatagram_unix.c.s
.PHONY : system/BDatagram_unix.c.s

system/BNetwork.o: system/BNetwork.c.o

.PHONY : system/BNetwork.o

# target to build an object file
system/BNetwork.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BNetwork.c.o
.PHONY : system/BNetwork.c.o

system/BNetwork.i: system/BNetwork.c.i

.PHONY : system/BNetwork.i

# target to preprocess a source file
system/BNetwork.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BNetwork.c.i
.PHONY : system/BNetwork.c.i

system/BNetwork.s: system/BNetwork.c.s

.PHONY : system/BNetwork.s

# target to generate assembly for a file
system/BNetwork.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BNetwork.c.s
.PHONY : system/BNetwork.c.s

system/BReactor_badvpn.o: system/BReactor_badvpn.c.o

.PHONY : system/BReactor_badvpn.o

# target to build an object file
system/BReactor_badvpn.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BReactor_badvpn.c.o
.PHONY : system/BReactor_badvpn.c.o

system/BReactor_badvpn.i: system/BReactor_badvpn.c.i

.PHONY : system/BReactor_badvpn.i

# target to preprocess a source file
system/BReactor_badvpn.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BReactor_badvpn.c.i
.PHONY : system/BReactor_badvpn.c.i

system/BReactor_badvpn.s: system/BReactor_badvpn.c.s

.PHONY : system/BReactor_badvpn.s

# target to generate assembly for a file
system/BReactor_badvpn.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BReactor_badvpn.c.s
.PHONY : system/BReactor_badvpn.c.s

system/BSignal.o: system/BSignal.c.o

.PHONY : system/BSignal.o

# target to build an object file
system/BSignal.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BSignal.c.o
.PHONY : system/BSignal.c.o

system/BSignal.i: system/BSignal.c.i

.PHONY : system/BSignal.i

# target to preprocess a source file
system/BSignal.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BSignal.c.i
.PHONY : system/BSignal.c.i

system/BSignal.s: system/BSignal.c.s

.PHONY : system/BSignal.s

# target to generate assembly for a file
system/BSignal.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BSignal.c.s
.PHONY : system/BSignal.c.s

system/BTime.o: system/BTime.c.o

.PHONY : system/BTime.o

# target to build an object file
system/BTime.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BTime.c.o
.PHONY : system/BTime.c.o

system/BTime.i: system/BTime.c.i

.PHONY : system/BTime.i

# target to preprocess a source file
system/BTime.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BTime.c.i
.PHONY : system/BTime.c.i

system/BTime.s: system/BTime.c.s

.PHONY : system/BTime.s

# target to generate assembly for a file
system/BTime.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BTime.c.s
.PHONY : system/BTime.c.s

system/BUnixSignal.o: system/BUnixSignal.c.o

.PHONY : system/BUnixSignal.o

# target to build an object file
system/BUnixSignal.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BUnixSignal.c.o
.PHONY : system/BUnixSignal.c.o

system/BUnixSignal.i: system/BUnixSignal.c.i

.PHONY : system/BUnixSignal.i

# target to preprocess a source file
system/BUnixSignal.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BUnixSignal.c.i
.PHONY : system/BUnixSignal.c.i

system/BUnixSignal.s: system/BUnixSignal.c.s

.PHONY : system/BUnixSignal.s

# target to generate assembly for a file
system/BUnixSignal.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/system/BUnixSignal.c.s
.PHONY : system/BUnixSignal.c.s

tun2socks/SocksUdpGwClient.o: tun2socks/SocksUdpGwClient.c.o

.PHONY : tun2socks/SocksUdpGwClient.o

# target to build an object file
tun2socks/SocksUdpGwClient.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/tun2socks/SocksUdpGwClient.c.o
.PHONY : tun2socks/SocksUdpGwClient.c.o

tun2socks/SocksUdpGwClient.i: tun2socks/SocksUdpGwClient.c.i

.PHONY : tun2socks/SocksUdpGwClient.i

# target to preprocess a source file
tun2socks/SocksUdpGwClient.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/tun2socks/SocksUdpGwClient.c.i
.PHONY : tun2socks/SocksUdpGwClient.c.i

tun2socks/SocksUdpGwClient.s: tun2socks/SocksUdpGwClient.c.s

.PHONY : tun2socks/SocksUdpGwClient.s

# target to generate assembly for a file
tun2socks/SocksUdpGwClient.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/tun2socks/SocksUdpGwClient.c.s
.PHONY : tun2socks/SocksUdpGwClient.c.s

tun2socks/tun2socks.o: tun2socks/tun2socks.c.o

.PHONY : tun2socks/tun2socks.o

# target to build an object file
tun2socks/tun2socks.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/tun2socks/tun2socks.c.o
.PHONY : tun2socks/tun2socks.c.o

tun2socks/tun2socks.i: tun2socks/tun2socks.c.i

.PHONY : tun2socks/tun2socks.i

# target to preprocess a source file
tun2socks/tun2socks.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/tun2socks/tun2socks.c.i
.PHONY : tun2socks/tun2socks.c.i

tun2socks/tun2socks.s: tun2socks/tun2socks.c.s

.PHONY : tun2socks/tun2socks.s

# target to generate assembly for a file
tun2socks/tun2socks.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/tun2socks/tun2socks.c.s
.PHONY : tun2socks/tun2socks.c.s

tuntap/BTap.o: tuntap/BTap.c.o

.PHONY : tuntap/BTap.o

# target to build an object file
tuntap/BTap.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/tuntap/BTap.c.o
.PHONY : tuntap/BTap.c.o

tuntap/BTap.i: tuntap/BTap.c.i

.PHONY : tuntap/BTap.i

# target to preprocess a source file
tuntap/BTap.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/tuntap/BTap.c.i
.PHONY : tuntap/BTap.c.i

tuntap/BTap.s: tuntap/BTap.c.s

.PHONY : tuntap/BTap.s

# target to generate assembly for a file
tuntap/BTap.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/tuntap/BTap.c.s
.PHONY : tuntap/BTap.c.s

udpgw_client/UdpGwClient.o: udpgw_client/UdpGwClient.c.o

.PHONY : udpgw_client/UdpGwClient.o

# target to build an object file
udpgw_client/UdpGwClient.c.o:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/udpgw_client/UdpGwClient.c.o
.PHONY : udpgw_client/UdpGwClient.c.o

udpgw_client/UdpGwClient.i: udpgw_client/UdpGwClient.c.i

.PHONY : udpgw_client/UdpGwClient.i

# target to preprocess a source file
udpgw_client/UdpGwClient.c.i:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/udpgw_client/UdpGwClient.c.i
.PHONY : udpgw_client/UdpGwClient.c.i

udpgw_client/UdpGwClient.s: udpgw_client/UdpGwClient.c.s

.PHONY : udpgw_client/UdpGwClient.s

# target to generate assembly for a file
udpgw_client/UdpGwClient.c.s:
	$(MAKE) -f CMakeFiles/tun2socks.dir/build.make CMakeFiles/tun2socks.dir/udpgw_client/UdpGwClient.c.s
.PHONY : udpgw_client/UdpGwClient.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... tun2socks"
	@echo "... base/BLog.o"
	@echo "... base/BLog.i"
	@echo "... base/BLog.s"
	@echo "... base/BLog_syslog.o"
	@echo "... base/BLog_syslog.i"
	@echo "... base/BLog_syslog.s"
	@echo "... base/BPending.o"
	@echo "... base/BPending.i"
	@echo "... base/BPending.s"
	@echo "... base/DebugObject.o"
	@echo "... base/DebugObject.i"
	@echo "... base/DebugObject.s"
	@echo "... flow/BufferWriter.o"
	@echo "... flow/BufferWriter.i"
	@echo "... flow/BufferWriter.s"
	@echo "... flow/PacketBuffer.o"
	@echo "... flow/PacketBuffer.i"
	@echo "... flow/PacketBuffer.s"
	@echo "... flow/PacketPassConnector.o"
	@echo "... flow/PacketPassConnector.i"
	@echo "... flow/PacketPassConnector.s"
	@echo "... flow/PacketPassFairQueue.o"
	@echo "... flow/PacketPassFairQueue.i"
	@echo "... flow/PacketPassFairQueue.s"
	@echo "... flow/PacketPassInterface.o"
	@echo "... flow/PacketPassInterface.i"
	@echo "... flow/PacketPassInterface.s"
	@echo "... flow/PacketProtoDecoder.o"
	@echo "... flow/PacketProtoDecoder.i"
	@echo "... flow/PacketProtoDecoder.s"
	@echo "... flow/PacketProtoEncoder.o"
	@echo "... flow/PacketProtoEncoder.i"
	@echo "... flow/PacketProtoEncoder.s"
	@echo "... flow/PacketProtoFlow.o"
	@echo "... flow/PacketProtoFlow.i"
	@echo "... flow/PacketProtoFlow.s"
	@echo "... flow/PacketRecvInterface.o"
	@echo "... flow/PacketRecvInterface.i"
	@echo "... flow/PacketRecvInterface.s"
	@echo "... flow/PacketStreamSender.o"
	@echo "... flow/PacketStreamSender.i"
	@echo "... flow/PacketStreamSender.s"
	@echo "... flow/SinglePacketBuffer.o"
	@echo "... flow/SinglePacketBuffer.i"
	@echo "... flow/SinglePacketBuffer.s"
	@echo "... flow/StreamPassInterface.o"
	@echo "... flow/StreamPassInterface.i"
	@echo "... flow/StreamPassInterface.s"
	@echo "... flow/StreamRecvInterface.o"
	@echo "... flow/StreamRecvInterface.i"
	@echo "... flow/StreamRecvInterface.s"
	@echo "... flowextra/PacketPassInactivityMonitor.o"
	@echo "... flowextra/PacketPassInactivityMonitor.i"
	@echo "... flowextra/PacketPassInactivityMonitor.s"
	@echo "... libancillary/fd_recv.o"
	@echo "... libancillary/fd_recv.i"
	@echo "... libancillary/fd_recv.s"
	@echo "... libancillary/fd_send.o"
	@echo "... libancillary/fd_send.i"
	@echo "... libancillary/fd_send.s"
	@echo "... lwip/custom/sys.o"
	@echo "... lwip/custom/sys.i"
	@echo "... lwip/custom/sys.s"
	@echo "... lwip/src/core/def.o"
	@echo "... lwip/src/core/def.i"
	@echo "... lwip/src/core/def.s"
	@echo "... lwip/src/core/inet_chksum.o"
	@echo "... lwip/src/core/inet_chksum.i"
	@echo "... lwip/src/core/inet_chksum.s"
	@echo "... lwip/src/core/init.o"
	@echo "... lwip/src/core/init.i"
	@echo "... lwip/src/core/init.s"
	@echo "... lwip/src/core/ipv4/autoip.o"
	@echo "... lwip/src/core/ipv4/autoip.i"
	@echo "... lwip/src/core/ipv4/autoip.s"
	@echo "... lwip/src/core/ipv4/icmp.o"
	@echo "... lwip/src/core/ipv4/icmp.i"
	@echo "... lwip/src/core/ipv4/icmp.s"
	@echo "... lwip/src/core/ipv4/igmp.o"
	@echo "... lwip/src/core/ipv4/igmp.i"
	@echo "... lwip/src/core/ipv4/igmp.s"
	@echo "... lwip/src/core/ipv4/ip4.o"
	@echo "... lwip/src/core/ipv4/ip4.i"
	@echo "... lwip/src/core/ipv4/ip4.s"
	@echo "... lwip/src/core/ipv4/ip4_addr.o"
	@echo "... lwip/src/core/ipv4/ip4_addr.i"
	@echo "... lwip/src/core/ipv4/ip4_addr.s"
	@echo "... lwip/src/core/ipv4/ip_frag.o"
	@echo "... lwip/src/core/ipv4/ip_frag.i"
	@echo "... lwip/src/core/ipv4/ip_frag.s"
	@echo "... lwip/src/core/ipv6/dhcp6.o"
	@echo "... lwip/src/core/ipv6/dhcp6.i"
	@echo "... lwip/src/core/ipv6/dhcp6.s"
	@echo "... lwip/src/core/ipv6/ethip6.o"
	@echo "... lwip/src/core/ipv6/ethip6.i"
	@echo "... lwip/src/core/ipv6/ethip6.s"
	@echo "... lwip/src/core/ipv6/icmp6.o"
	@echo "... lwip/src/core/ipv6/icmp6.i"
	@echo "... lwip/src/core/ipv6/icmp6.s"
	@echo "... lwip/src/core/ipv6/inet6.o"
	@echo "... lwip/src/core/ipv6/inet6.i"
	@echo "... lwip/src/core/ipv6/inet6.s"
	@echo "... lwip/src/core/ipv6/ip6.o"
	@echo "... lwip/src/core/ipv6/ip6.i"
	@echo "... lwip/src/core/ipv6/ip6.s"
	@echo "... lwip/src/core/ipv6/ip6_addr.o"
	@echo "... lwip/src/core/ipv6/ip6_addr.i"
	@echo "... lwip/src/core/ipv6/ip6_addr.s"
	@echo "... lwip/src/core/ipv6/ip6_frag.o"
	@echo "... lwip/src/core/ipv6/ip6_frag.i"
	@echo "... lwip/src/core/ipv6/ip6_frag.s"
	@echo "... lwip/src/core/ipv6/mld6.o"
	@echo "... lwip/src/core/ipv6/mld6.i"
	@echo "... lwip/src/core/ipv6/mld6.s"
	@echo "... lwip/src/core/ipv6/nd6.o"
	@echo "... lwip/src/core/ipv6/nd6.i"
	@echo "... lwip/src/core/ipv6/nd6.s"
	@echo "... lwip/src/core/mem.o"
	@echo "... lwip/src/core/mem.i"
	@echo "... lwip/src/core/mem.s"
	@echo "... lwip/src/core/memp.o"
	@echo "... lwip/src/core/memp.i"
	@echo "... lwip/src/core/memp.s"
	@echo "... lwip/src/core/netif.o"
	@echo "... lwip/src/core/netif.i"
	@echo "... lwip/src/core/netif.s"
	@echo "... lwip/src/core/pbuf.o"
	@echo "... lwip/src/core/pbuf.i"
	@echo "... lwip/src/core/pbuf.s"
	@echo "... lwip/src/core/stats.o"
	@echo "... lwip/src/core/stats.i"
	@echo "... lwip/src/core/stats.s"
	@echo "... lwip/src/core/tcp.o"
	@echo "... lwip/src/core/tcp.i"
	@echo "... lwip/src/core/tcp.s"
	@echo "... lwip/src/core/tcp_in.o"
	@echo "... lwip/src/core/tcp_in.i"
	@echo "... lwip/src/core/tcp_in.s"
	@echo "... lwip/src/core/tcp_out.o"
	@echo "... lwip/src/core/tcp_out.i"
	@echo "... lwip/src/core/tcp_out.s"
	@echo "... lwip/src/core/timers.o"
	@echo "... lwip/src/core/timers.i"
	@echo "... lwip/src/core/timers.s"
	@echo "... lwip/src/core/udp.o"
	@echo "... lwip/src/core/udp.i"
	@echo "... lwip/src/core/udp.s"
	@echo "... socksclient/BSocksClient.o"
	@echo "... socksclient/BSocksClient.i"
	@echo "... socksclient/BSocksClient.s"
	@echo "... system/BConnection_common.o"
	@echo "... system/BConnection_common.i"
	@echo "... system/BConnection_common.s"
	@echo "... system/BConnection_unix.o"
	@echo "... system/BConnection_unix.i"
	@echo "... system/BConnection_unix.s"
	@echo "... system/BDatagram_unix.o"
	@echo "... system/BDatagram_unix.i"
	@echo "... system/BDatagram_unix.s"
	@echo "... system/BNetwork.o"
	@echo "... system/BNetwork.i"
	@echo "... system/BNetwork.s"
	@echo "... system/BReactor_badvpn.o"
	@echo "... system/BReactor_badvpn.i"
	@echo "... system/BReactor_badvpn.s"
	@echo "... system/BSignal.o"
	@echo "... system/BSignal.i"
	@echo "... system/BSignal.s"
	@echo "... system/BTime.o"
	@echo "... system/BTime.i"
	@echo "... system/BTime.s"
	@echo "... system/BUnixSignal.o"
	@echo "... system/BUnixSignal.i"
	@echo "... system/BUnixSignal.s"
	@echo "... tun2socks/SocksUdpGwClient.o"
	@echo "... tun2socks/SocksUdpGwClient.i"
	@echo "... tun2socks/SocksUdpGwClient.s"
	@echo "... tun2socks/tun2socks.o"
	@echo "... tun2socks/tun2socks.i"
	@echo "... tun2socks/tun2socks.s"
	@echo "... tuntap/BTap.o"
	@echo "... tuntap/BTap.i"
	@echo "... tuntap/BTap.s"
	@echo "... udpgw_client/UdpGwClient.o"
	@echo "... udpgw_client/UdpGwClient.i"
	@echo "... udpgw_client/UdpGwClient.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

